apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  db_user: cG9zdGdyZXMueG5jeWZ0amJ2emluZnZsc2J1Y3g=
  db_password: WnFBQU1ldFBrc0NWcnI4SA==
  db_host: YXdzLTAtdXMtZWFzdC0xLnBvb2xlci5zdXBhYmFzZS5jb20=
  db_port: NjU0Mw==
  db_name: cG9zdGdyZXM=



